#!/usr/bin/env bash

# create our VPC

VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=shubh-vpc}]' \
--region us-east-1  \
--query Vpc.VpcId \
--output text)

echo "VPC_ID: $VPC_ID"

# create our IGW

IGW_ID=$(aws ec2 create-internet-gateway \
--query InternetGasteway.InternetGatewayId
--output text
)

echo "IGW_ID: $IGW_ID"

# attach our IGW

aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

# create a new subnet

# explicitly associate subnet
 
# add aroute for our RT to our IGW