#!/usr/bin/env bash


# Check if an argument is provided
if [ -z "$1" ]; then
   echo "Error: No argument provided."
else
   export VPC_ID="$1"   
fi

# dettach the IGW



# delete VPC

aws ec2 delete-vpc --vpc-id $VPC_ID